### PR TITLE
python3 

### PR DESCRIPTION
**Pull request by ayushnawal**
@quozl please review!

### CODE REVIEW

**Review by srevinsaju — CHANGES_REQUESTED** [review]
@ayushnawal , changes so far is good, but it would be better if these commits from iKnowActivity had been also used here too

1: Add toolbar https://github.com/sugarlabs/iknowIndia/pull/7/commits/a9e06a751c4ff5166736ca06afe3f5c290b9510c
2: Safe exit of sugargame instance https://github.com/sugarlabs/iknowIndia/pull/7/commits/9e030eebb83d8336c4294b1fc8cbe3a62fd74807 and https://github.com/sugarlabs/iknowIndia/pull/7/commits/1a2375bc9a1830e8f796fc3bca5d4e65c0d9670f

Tested on Sugar VM 0.116. Works good

**Comment by ayushnawal** [comment]
@srevinsaju agreed. Thanks

**Comment by ayushnawal** [comment]
tested.

@quozl please review.

**Comment by ayushnawal** [comment]
saw that [pr](https://github.com/sugarlabs/iknowIndia/pull/7) again.

once @srevinsaju fixes it and @quozl approves it, I will make a separate pull request for that similar feature addition.

Porting changes are reviewed by @srevinsaju 

works well for me too.

ready to merge :)

**Comment by ayushnawal** [comment]
@quozl

**Comment by quozl** [comment]
Thanks.  Reviewed.  Are you sure `str` is needed?

I've also posted [Ideal futures for the "I Know" Sugar activities](http://lists.sugarlabs.org/archive/sugar-devel/2020-January/057685.html) to give some guidance.

**Comment by ayushnawal** [comment]
Done, absolutely right, str not needed there with python 3.

Reading [Ideal futures for the "I Know" Sugar activities](http://lists.sugarlabs.org/archive/sugar-devel/2020-January/057685.html) and suggestions that are given to it by various members on `sugar-devel` carefully.

Thanks. activity ready for port :rocket:

**Pull request merged**
